# Generated by Django 4.0.6 on 2022-07-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_rename_addess_zipcode_place_address_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address_street',
            field=models.CharField(max_length=40),
        ),
    ]
